name: Test

on:  
  push:
  workflow_dispatch:

jobs:
  TestIt:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.MULTI_LINE_3_VARS }}
        run: |
          ./test.sh
